pipeline

diff --git a/.github/workflows/smoke_test.yml b/.github/workflows/smoke_test.yml
--- a/.github/workflows/smoke_test.yml
+++ b/.github/workflows/smoke_test.yml
@@ -1,8 +1,7 @@
-name: Smoke testing for infra and networking
+name: Smoke Testing For Infra and Networking
 
 on:
   workflow_call:
-  workflow_dispatch:
 
 permissions:
   id-token: write
@@ -12,11 +11,6 @@ jobs:
   smoke:
     runs-on: ubuntu-latest
 
-    env:
-      AWS_REGION: ap-south-1
-      S3_BUCKET: 306158389325-devops-scripts
-      SCRIPT_NAME: smoke_test.py
-
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
@@ -25,13 +19,16 @@ jobs:
         uses: aws-actions/configure-aws-credentials@v4
         with:
           role-to-assume: arn:aws:iam::306158389325:role/GitHub-action-deploy-role-policy
-          aws-region: ${{ env.AWS_REGION }}
+          aws-region: ap-south-1
+
+      - name: All files
+        run: ls -la
 
       - name: Upload smoke_test.py on AWS
         run: |
-          aws s3 cp "$SCRIPT_NAME" \
-            "s3://$S3_BUCKET/$SCRIPT_NAME" \
-            --region "$AWS_REGION"
+          aws s3 cp smoke_test.py \
+            s3://306158389325-devops-scripts/smoke_test.py \
+            --region ap-south-1
 
       - name: Run Smoke Test on Fleet
         id: smoke
@@ -46,7 +43,7 @@ jobs:
             ]}' \
             --query 'Command.CommandId' \
             --output text \
-            --region "$AWS_REGION")
+            --region ap-south-1)
 
           echo "cmd_id=$CMD_ID" >> "$GITHUB_OUTPUT"
           echo "Command ID: $CMD_ID"
@@ -58,18 +55,17 @@ jobs:
           aws ssm list-command-invocations \
             --command-id "${{ steps.smoke.outputs.cmd_id }}" \
             --details \
-            --region "$AWS_REGION" \
+            --region ap-south-1 \
             --output text
 
           FAILED=$(aws ssm list-command-invocations \
             --command-id "${{ steps.smoke.outputs.cmd_id }}" \
             --query "length(CommandInvocations[?Status=='Failed'])" \
             --output text \
-            --region "$AWS_REGION")
+            --region ap-south-1)
 
-          if [ "$FAILED" -gt 0 ]; then
-            echo "::error::Health Check Failed on $FAILED instances"
-            exit 1
-          fi
+          [ "$FAILED" -gt 0 ] && \ 
+          echo "::error::Smoke Test $FAILED instances" && \ 
+          exit 1
 
           echo "Smoke Test Passed ✅"
