pipeline

diff --git a/.github/workflows/test_fleet_health.yml b/.github/workflows/test_fleet_health.yml
--- a/.github/workflows/test_fleet_health.yml
+++ b/.github/workflows/test_fleet_health.yml
@@ -1,7 +1,7 @@
-name: Test Fleet health and Env variable
+name: Test fleet
 
 on:
-  workflow_call:
+  workflow_dispatch:
 
 permissions:
   id-token: write
@@ -17,19 +17,44 @@ jobs:
           role-to-assume: arn:aws:iam::306158389325:role/GitHub-action-deploy-role-policy
           aws-region: ap-south-1
 
-      - name: Print Private IPs
+      - name: Fleet Health Checks
+        id: health
         run: |
           CMD_ID=$(aws ssm send-command \
             --targets "Key=tag:App,Values=flask" \
             --document-name "AWS-RunShellScript" \
-            --parameters '{"commands":["hostname -I"]}' \
-            --query 'Command.CommandId' \
-            --output text)
-
-          sleep 30
-
+            --parameters '{"commands":[
+              "hostname -I",
+              "docker --version 2>/dev/null  echo DOCKER NOT INSTALLED",
+              "aws --version 2>/dev/null  echo AWS CLI NOT INSTALLED",
+              "mysql --version 2>/dev/null || echo DOCKER NOT INSTALLED",
+              "aws ssm get-parameters-by-path --path /application/banking --with-decryption --region ap-south-1"
+              ]}' \
+            --query 'Command.CommandId' --output text \
+            --region ap-south-1)
+          echo "cmd_id"=$"CMD_ID" >> $GITHUB_OUTPUT
+      
+      
+      - name: Show Results
+        run:   
+          sleep 20
           aws ssm list-command-invocations \
-            --command-id "$CMD_ID" \
-            --details \
-            --query "CommandInvocations[*].{Instance:InstanceId,Output:CommandPlugins[0].Output}" \
-            --output table
+            --command-id "${{steps.health.outputs.cmd_id}}" --details \
+            --region ap-south-1
+            --query "CommandInvocations[*].{Instance:InstanceId,Status,IP:CommandPlugins[0].Output}" \
+            --output text
+          
+          FAILED=$(aws ssm list-command-invocations \
+            --command-id "${{steps.health.outputs.cmd_id}}" --details \
+            --query "length(CommandInvocations[?Status=='Failed'])" \
+            --output text \
+            --region ap-south-1
+            )
+
+          [ "$FAILED" -gt 0 ] && \
+          echo "::error::Health Check Failed on $FAILED instances" && \
+          exit 1
+
+          echo "ALL Instances Healthy ✅"
+
+        
